## Матрицы и матричные операции. Часть 1

Все задания рекомендуется делать вручную, затем проверяя полученные результаты с использованием numpy.

__Задание 1__  
Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Матричное умножение возможно, когда количество столбцов первой матрицы равно количеству строк второй, а каждый новый элемент это скалярное произведение вектор-строки первой матрицы на вектор-столбец второй.  
Исходя из вышесказанного:

   а) произведение матриц не определено;
    
   б) $AB$ — произведение определено, размерность $2\times 3$; $BA$ - не определено;
    
   в) $AB$ — произведение определено, размерность $8\times 8$; $BA$ - определено, размерность $3\times 3$;
    
   г) $AB$ — произведение определено, размерность $4\times 4$; $BA$ - определено, размерность $4\times 4$.

In [1]:
import numpy as np

def ab_ba(size_a, size_b):
    try:
        np.dot(np.zeros(size_a), np.zeros(size_b))
    except ValueError:
        print(f'произведения матриц AB не определено')
    else:
        print(f'произведения матриц AB определено, размерность {np.dot(np.zeros(size_a), np.zeros(size_b)).shape}')
    try:
        np.dot(np.zeros(size_b), np.zeros(size_a))
    except ValueError:
        print(f'произведения матриц BA не определено')
    else:
        print(f'произведения матриц BA определено, размерность {np.dot(np.zeros(size_b), np.zeros(size_a)).shape}')

In [2]:
ab_ba((4,2),(4,2))
ab_ba((2,5),(5,3))
ab_ba((8,3),(3,8))
ab_ba((4,4),(4,4))

произведения матриц AB не определено
произведения матриц BA не определено
произведения матриц AB определено, размерность (2, 3)
произведения матриц BA не определено
произведения матриц AB определено, размерность (8, 8)
произведения матриц BA определено, размерность (3, 3)
произведения матриц AB определено, размерность (4, 4)
произведения матриц BA определено, размерность (4, 4)


__Задание 2__  
Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix}=\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$

$A\cdot B=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} \cdot \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}=\begin{pmatrix}
1\cdot4 + -2\cdot0 & 1\cdot(-1)-2\cdot5\\ 
3\cdot4 + 0\cdot0 & 3\cdot(-1)+0\cdot5
\end{pmatrix}=\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$
$B\cdot A=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} \cdot \begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}=\begin{pmatrix}
4\cdot1 -1\cdot3 & 4\cdot(-2) -1\cdot0\\ 
0\cdot1 + 5\cdot3 & 0\cdot(-2)+5\cdot0
\end{pmatrix}=\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}.$

In [3]:
A = np.array([[1,-2],[3,0]])
B = np.array([[4,-1],[0,5]])
print(f'A+B\n{A+B}\n\n\
AB\n{A.dot(B)}\n\n\
BA\n{B.dot(A)}')

A+B
[[ 5 -3]
 [ 3  5]]

AB
[[  4 -11]
 [ 12  -3]]

BA
[[ 1 -8]
 [15  0]]


__Задание 3__  
Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C=\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}+\begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix}+\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}=\begin{pmatrix}
3+0+8 & 21-10-16\\ 
9-4+4 & -18+2+4
\end{pmatrix}=\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [4]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])

3*A-2*B+4*C

array([[ 11,  -5],
       [  9, -12]])

__Задание 4__  
Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\end{pmatrix}$.

$AA^{T}=\begin{pmatrix}
4\cdot4 + 1\cdot1 & 4\cdot5 + 1\cdot(-2) & 4\cdot2 + 1\cdot3\\ 
5\cdot4 - 2\cdot1 & 5\cdot5 - 2\cdot(-2) & 5\cdot2 - 2\cdot3\\
2\cdot4 + 3\cdot1 & 2\cdot5 + 3\cdot(-2) & 2\cdot2 + 3\cdot3\end{pmatrix}=
\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\
11 & 4 & 13\end{pmatrix}$

$A^{T}A=\begin{pmatrix}
4\cdot4 + 5\cdot5 + 2\cdot2 & 4\cdot1 + 5\cdot(-2) + 2\cdot3\\ 
1\cdot4 - 2\cdot5 + 3\cdot2 & 1\cdot1 - 2\cdot(-2) + 3\cdot3\end{pmatrix}=
\begin{pmatrix}
45 & 0\\
0 & 14\end{pmatrix}$

In [5]:
A = np.array([[4,1],[5,-2],[2,3]])
print(f'A*AT\n{A.dot(A.T)}\n')
print(f'AT*A\n{A.T.dot(A)}')

A*AT
[[17 18 11]
 [18 29  4]
 [11  4 13]]

AT*A
[[45  0]
 [ 0 14]]


__Задание 5*__  
Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [6]:
def multiplication(a, b):
    if len(a[0]) != len(b):
        print(f'Не определено произведение! Количество столбцов первой матрицы не равно количеству строк второй.')
    else:
        return print([[sum([el*b[j][col] for j,el in enumerate(row)]) for col in range(len(b[0]))] for i,row in enumerate(a)])

In [7]:
a = [[4,1],[5,-2],[2,3]]
b = [[4,5,2],[1,-2,3]]
multiplication(a, b)
multiplication(b, a)
c = [[1,1],[2,2],[3,3]]
d = [[4,4],[5,5],[6,6]]
multiplication(c, d)

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]
[[45, 0], [0, 14]]
Не определено произведение! Количество столбцов первой матрицы не равно количеству строк второй.


## Матрицы и матричные операции. Часть 2

__Задание 1__  

Вычислить определитель:

   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

   б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$
    
   в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

a)

$\triangle= sinx \cdot sinx - (-cosx)\cdot cosx= sin^2x + cos^2x = 1;$   

In [8]:
import sympy as sym

x = sym.symbols('x')

A = sym.Matrix([[sym.sin(x),sym.cos(x)],[-sym.cos(x),sym.sin(x)]])
A

Matrix([
[ sin(x), cos(x)],
[-cos(x), sin(x)]])

In [9]:
sym.simplify(sym.det(A))

1

б)
    
$\triangle=\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix}=9\cdot\begin{vmatrix}
4 & 2 \\ 
0 & 5 \end{vmatrix}=9\cdot(4\cdot5-0\cdot2)=180;$

In [10]:
np.linalg.det(np.array([[4,2,3],[0,5,1],[0,0,9]]))

180.0

в)

$\triangle\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}=\begin{vmatrix}
1 & 2 & 3\\ 
3 & 3 & 3\\ 
3 & 3 & 3
\end{vmatrix}=0.$

In [11]:
print(f'Определитель:\n{np.linalg.det(np.array([[1,2,3],[4,5,6],[7,8,9]])):.0f}')

Определитель:
0


__Задание 2__  

Определитель матрицы $A$ равен $4$. Найти:

   а) $det(A^{2})=det(A)\cdot det(A)=4^2=16$;
    
   б) $det(A^{T})=det(A)=4$;
    
   в) $det(2A)=2det(A)=8$.

__Задание 3__  

Доказать, что матрица

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
   
вырожденная.

Умножим первую строку на 2 и прибавим к третьей:
$\triangle\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}=\begin{pmatrix}
-2 & 7 & -3\\ 
0 & 0 & 0\\ 
-3 & 7 & 13
\end{pmatrix}=0$

In [12]:
np.linalg.det(np.array([[-2,7,-3],[4,-14,6],[-3,7,13]]))

0.0

__Задание 4__  

Найти ранг матрицы:

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

а) В исходной матрице третья строка является линейной комбинацией первых двух, поэтому ее можно выкинуть:
$rank = \begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix}=\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\end{pmatrix}=2$


In [13]:
np.linalg.matrix_rank(np.array([[1,2,3],[1,1,1,],[2,3,4]]))

2

б)  В исходной матрице третья строка является линейной комбинацией первых двух, поэтому ее можно выкинуть:
$rank=\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}=\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\  
2 & 3 & 5 & 6
\end{pmatrix}=3.$

In [14]:
np.linalg.matrix_rank(np.array([[0,0,2,1],[0,0,2,2],[0,0,4,3],[2,3,5,6]]))

3