## Системы линейных уравнений. Часть 1

__Задание 1__  
Решить систему уравнений методом Гаусса:

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$

__Решение__<br>
<br>
$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
2 & 1 & -1 & 1\\
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\
0 & -1 & 1 & 5\\
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}
$<br>
Система имеет бесконечное множество решений. Найдем общее решение системы уравнений:<br>
$\begin{cases}
x_1+x_2-x_3-2x_4=0\\
-x_2+x_3+5x_4=-2\\
-2x_3+3x_4=4
\end{cases}
\rightarrow
\begin{cases}
x_1+x_2-x_3-2x_4=0\\
x_2=x_3+5x_4+2\\
x_3=\frac{3x_4}{2}-2\\
x_4=c
\end{cases}
\rightarrow
\begin{cases}
x_1=-x_2+\frac{3c}{2}-2+2c\\
x_2=\frac{3c}{2}-2+5c+2\\
x_3=\frac{3c}{2}-2\\
x_4=c
\end{cases}
\rightarrow
\begin{cases}
x_1=-3c-2\\
x_2=\frac{13c}{2}\\
x_3=\frac{3c}{2}-2\\
x_4=c
\end{cases}$

Найдем частное решение системы уравнений при $x_4=c=2$:<br>
$\begin{cases}
x_1=-8\\
x_2=13\\
x_3=1\\
x_4=2
\end{cases}$

Проверим полученное значение, подставив в исходную систему:<br>
<br>
$\begin{cases}
-8+13-1-4=0, \\
-16+13-1+2=-2, \\
-8+13-3+2=4.
\end{cases}$<br><br>
__Ответ__ $x=(-3c-2,\frac{13c}{2},\frac{3c}{2}-2,c)$

__Задание 2__  
Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$

In [1]:
import numpy as np
import numpy.linalg as LA

def is_consistent(A, b):
    n = len(A[0])
    A_ = np.append(A, b.T, axis=1)
    print(f'Расширенная матрица системы уравнений:\n{A_}')
    print(f'Ранг матрицы - {LA.matrix_rank(A)}, ранг расширенной матрицы - {LA.matrix_rank(A_)}')
    if LA.matrix_rank(A) == LA.matrix_rank(A_):
        if LA.matrix_rank(A) == n:
            print(f'Система линейных уравнений совместная(есть решения), определенная (единственное решение).')
        else:
            print(f'Система линейных уравнений совместная(есть решения), неопределенная (множество решений).')
    else:
        print(f'Система линейных уравнений несовместная(не имеет решений).')    

__Решение__  

а) $\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\
2 & -5 & -3 \\
1 & 1 & -1
\end{matrix}
\right |
\begin{matrix}
4\\
-17\\
0
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
2 & -5 & -3 \\
3 & -1 & 1
\end{matrix}
\right |
\begin{matrix}
0\\
-17\\
4
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
0 & -7 & -1 \\
0 & -4 & 4
\end{matrix}
\right |
\begin{matrix}
0\\
-17\\
4
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 \\
0 & -7 & -1 \\
0 & -8 & 0
\end{matrix}
\right |
\begin{matrix}
0\\
-17\\
-16
\end{matrix}
\end{pmatrix}
$<br><br>
__Ответ__ Система уравнений определенная и совместная, т.к. ранг матрицы равен рангу расширенной матрицы и количеству переменных.

In [2]:
A = np.array([[3,-1,1],[2,-5,-3],[1,1,-1]])
b = np.array([[4,-17,0]])
is_consistent(A, b)

Расширенная матрица системы уравнений:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]
Ранг матрицы - 3, ранг расширенной матрицы - 3
Система линейных уравнений совместная(есть решения), определенная (единственное решение).


б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$<br>
__Решение__  

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\
1 & -2 & 3 \\
3 & -6 & 9
\end{matrix}
\right |
\begin{matrix}
1\\
-2\\
5
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
2 & -4 & 6 \\
3 & -6 & 9
\end{matrix}
\right |
\begin{matrix}
-2\\
1\\
5
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{matrix}
\right |
\begin{matrix}
-2\\
5\\
11
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & -2 & 3 \\
0 & 0 & 0 \\
0 & 0 & 0
\end{matrix}
\right |
\begin{matrix}
-2\\
5\\
0
\end{matrix}
\end{pmatrix}
$<br><br>
__Ответ__ Система уравнений несовместная, т.к. ранг матрицы меньше ранга расширенной матрицы.

In [3]:
A = np.array([[2,-4,6],[1,-2,3],[3,-6,9]])
b = np.array([[1,-2,5]])
is_consistent(A, b)

Расширенная матрица системы уравнений:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]
Ранг матрицы - 1, ранг расширенной матрицы - 2
Система линейных уравнений несовместная(не имеет решений).


в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$<br>
__Решение__  

$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\
3 & 1 & 8
\end{matrix}
\right |
\begin{matrix}
4\\
-2
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 5 \\
0 & -5 & -23
\end{matrix}
\right |
\begin{matrix}
4\\
-14
\end{matrix}
\end{pmatrix}
$<br><br>
__Ответ__ Система уравнений совместная и неопределенная(недоопределенная), т.к. ранг матрицы равен рангу расширенной матрицы и меньше количества переменных. Т.е. система уравнений имеет множество решений.

In [4]:
A = np.array([[1,2,5],[3,1,-8]])
b = np.array([[4,-2]])
is_consistent(A, b)

Расширенная матрица системы уравнений:
[[ 1  2  5  4]
 [ 3  1 -8 -2]]
Ранг матрицы - 2, ранг расширенной матрицы - 2
Система линейных уравнений совместная(есть решения), неопределенная (множество решений).


__Задание 3__  
Проверить на совместность и выяснить, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$
<br><br>
__Ответ__  
В данном случае нет необходимости даже преобразовывать расширенную матрицу. Ранг расширенной матрицы равен рангу матрицы и количеству переменных, следовательно, данная система уравнений имеет единственное решение.  
$\begin{cases}
x_1+3x_2-2x_3+4x_4 = 3\\
5x_2+x_4 = 2\\
3x_3 = 4\\
2x_4 = 1
\end{cases}, \quad x=(\frac{83}{30},\frac{3}{10},\frac{4}{3},\frac{1}{2})
$

In [5]:
A = np.array([[1,3,-2,4],[0,5,0,1],[0,0,3,0],[0,0,0,2]])
b = np.array([[3,2,4,1]])
is_consistent(A, b)

Расширенная матрица системы уравнений:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]
Ранг матрицы - 4, ранг расширенной матрицы - 4
Система линейных уравнений совместная(есть решения), определенная (единственное решение).


__Задание 4__  
Дана система линейных уравнений, заданная расширенной матрицей

$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$

Найти соотношение между параметрами $a$, $b$ и $c$, при которых система является несовместной.

__Решение__  
$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}
\rightarrow
\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
3 & 3 & 3\\ 
3 & 3 & 3
\end{matrix}\right|
\begin{matrix}
a\\ 
b-a\\
c-b
\end{matrix}
\end{pmatrix}$<br>
Система является несовместной если ранг матрицы меньше ранга расширенной матрицы.  
То есть при условии - $b-a \neq c-b,\quad b \neq \frac{c+a}{2}$

## Системы линейных уравнений. Часть 2

__Задание 5__  
Написать на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [6]:
def cramer_rule(A, b):
    n = len(A)
    if n == len(A[0]):
        if LA.det(A) == 0:
            return print(f'Система уравнений вырождена!')
        x = []
        for i in range(n):
            A_=A.copy()
            for j in range(n):
                A_[j][i] = b[0][j]
            x.append(round(LA.det(A_)/LA.det(A)))
        return x
    else:
        print(f'Метод не применяется для неквадратных матриц!')

In [7]:
def find_roots(vec, matrix, start, end):
    roots = np.zeros(len(vec))
    i = start
    while i <= end:
        roots[abs(i)]=(vec[abs(i)]-sum(matrix[abs(i)]*roots))/matrix[abs(i)][abs(i)]
        i += 1
    return roots

In [8]:
def linear_LU(matrix_1,vec_b):
    n = len(matrix_1)
    u = matrix_1.copy()
    l = np.eye(n)    
    for i in range(n):
        for j in range(i+1,n):
            x = u[j][i]/u[i][i]
            u[j] = u[j]-x*u[i]
            l[j][i] = x
    print(f'Матрица L:\n{l}\n\
    Матрица U:\n{u}')
    y = find_roots(vec_b, l, 0, len(vec_b)-1)
    x = find_roots(y, u, -len(y)+1, 0)
    return f'Корни уравнения {x}'    

__Задание 1__  
Решить систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$<br><br>
$det(A)=\begin{pmatrix}
1 & -2\\
3 & -4\end{pmatrix}=
1*(-4)-3*(-2)=-4+6=2$ <br>
$det(A_1)=\begin{pmatrix}
1 & -2\\
7 & -4\end{pmatrix}=
1*(-4)-7*(-2)=-4+14=10, \quad
det(A_2)=\begin{pmatrix}
1 & 1\\
3 & 7\end{pmatrix}=
1*7-3*1=7-3=4
$<br><br>
$x_1=\frac{det(A_1)}{det(A)}=\frac{10}{2}=5, \quad
x_2=\frac{det(A_2)}{det(A)}=\frac{4}{2}=2$<br><br>
__Ответ:__
$x=(5,2)$

In [9]:
A = np.array([[1,-2],[3,-4]])
b = np.array([[1,7]])
cramer_rule(A,b)

[5.0, 2.0]

б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}
\rightarrow
\begin{pmatrix}
2 & -1 & 5\\
1 & 1 & -3\\
2 & 4 & 1\end{pmatrix},\quad \begin{pmatrix}
10\\
-2\\
1\end{pmatrix}$<br><br>

$det(A)=2\cdot\begin{pmatrix}
1 & -3\\
4 & 1\end{pmatrix}+1\cdot\begin{pmatrix}
1 & -3\\
2 & 1\end{pmatrix}+5\cdot\begin{pmatrix}
1 & 1\\
2 & 4\end{pmatrix}=
2*13+1*7+5*2=43$ <br>

$det(A_1)=\begin{pmatrix}
10 & -1 & 5\\
-2 & 1 & -3\\
1 & 4 & 1\end{pmatrix}=
10*13+1*(-2+3)+5*(-18-1)=86$ <br>

$det(A_2)=\begin{pmatrix}
2 & 10 & 5\\
1 & -2 & -3\\
2 & 1 & 1\end{pmatrix}=
2*(-2+3)-10*7+5*(1+4)=-43$ <br>

$det(A_3)=\begin{pmatrix}
2 & -1 & 10\\
1 & 1 & -2\\
2 & 4 & 1\end{pmatrix}=
2*(1+8)+1(1+4)+10*(4-2)=43$ <br>

$x_1=\frac{det(A_1)}{det(A)}=\frac{86}{43}=2, \quad
x_2=\frac{det(A_2)}{det(A)}=\frac{-43}{43}=-1, \quad
x_3=\frac{det(A_3)}{det(A)}=\frac{43}{43}=1$<br><br>
__Ответ:__
$x=(2,-1,1)$

In [10]:
A = np.array([[2,-1,5],[1,1,-3],[2,4,1]])
b = np.array([[10,-2,1]])
cramer_rule(A,b)

[2.0, -1.0, 1.0]

__Задание 2__  
Найти $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}, \quad
U=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 20 & 18
\end{pmatrix}=\begin{pmatrix}
1 & 2 & 4 \\ 
0 & 5 & 4 \\ 
0 & 0 & 2
\end{pmatrix}$<br><br>
$L=\begin{pmatrix}
1 & 0 & 0 \\ 
2 & 1 & 0 \\ 
3 & 4 & 1
\end{pmatrix}
$

In [11]:
# проверка полученных матриц:
u = np.array([[1,2,4],[0,5,4],[0,0,2]])
l = np.array([[1,0,0],[2,1,0],[3,4,1]])
np.dot(l,u)

array([[ 1,  2,  4],
       [ 2,  9, 12],
       [ 3, 26, 30]])

б)$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}, \quad
U=\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 15 & 23 & 6\\
0 & 18 & 45 & 17
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 21 & 11
\end{pmatrix}=
\begin{pmatrix}
1 & 1 & 2 & 4\\ 
0 & 3 & 4 & 1\\ 
0 & 0 & 3 & 1\\
0 & 0 & 0 & 4
\end{pmatrix}$<br><br>
$L=\begin{pmatrix}
1 & 0 & 0 & 0\\ 
2 & 1 & 0 & 0\\ 
3 & 5 & 1 & 0\\
4 & 6 & 7 & 1
\end{pmatrix}$

In [12]:
# проверка полученных матриц:
u = np.array([[1,1,2,4],[0,3,4,1],[0,0,3,1],[0,0,0,4]])
l = np.array([[1,0,0,0],[2,1,0,0],[3,5,1,0],[4,6,7,1]])
np.dot(l,u)

array([[ 1,  1,  2,  4],
       [ 2,  5,  8,  9],
       [ 3, 18, 29, 18],
       [ 4, 22, 53, 33]])

__Задание 3__  
Решить систему линейных уравнений методом $LU$-разложения

$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$

__Решение__  
$U=\begin{pmatrix}
2 & 1 & 3\\ 
11 & 7 & 5\\ 
9 & 8 & 4
\end{pmatrix}=
\begin{pmatrix}
2 & 1 & 3\\ 
0 & 3/2 & -23/2\\ 
0 & 7/2 & -19/2
\end{pmatrix}=
\begin{pmatrix}
2 & 1 & 3\\ 
0 & 3/2 & -23/2\\ 
0 & 0 & 52/3
\end{pmatrix}$<br><br>
$L=\begin{pmatrix}
1 & 0 & 0\\ 
11/2 & 1 & 0\\ 
9/2 & 7/3 & 1
\end{pmatrix}$<br><br>
$Ly=b$<br>
$\begin{cases}
y_1 = 1\\
\frac{11}{2}y_1+y_2 = -6\\
\frac{9}{2}y_1+\frac{7}{3}y_2 +y_3 = -5
\end{cases}, \quad
\begin{cases}
y_1 = 1\\
y_2 = -\frac{23}{2}\\
y_3 = \frac{52}{3}
\end{cases}$<br><br>
$Ux=y$<br>
$\begin{cases}
2x_1 + x_2 +3x_3= 1\\
\frac{3}{2}x_2-\frac{23}{2}x_3 = -\frac{23}{2}\\
\frac{52}{3}x_3= \frac{52}{3}
\end{cases}, \quad
\begin{cases}
x_1 = -1\\
x_2 = 0\\
x_3 = 1\\
\end{cases}$<br><br>
Проверим подстановкой:<br>
$\begin{cases}
2*(-1)+0+3*1=1 \\
11*(-1)+7*0+5*1=-6 \\
9*(-1)+8*0+4*1=-5
\end{cases}$

In [13]:
import sympy as sym

x1, x2, x3 = sym.symbols('x1, x2, x3')

A_ = sym.Matrix([[2,1,3,1],[11,7,5,-6],[9,8,4,-5]])
sym.solve_linear_system_LU(A_,[x1,x2,x3])

{x1: -1, x2: 0, x3: 1}

In [14]:
print(linear_LU(np.array([[2,1,3],[11,7,5],[9,8,4]],float),np.array([1,-6,-5])))

Матрица L:
[[1.         0.         0.        ]
 [5.5        1.         0.        ]
 [4.5        2.33333333 1.        ]]
    Матрица U:
[[  2.           1.           3.        ]
 [  0.           1.5        -11.5       ]
 [  0.           0.          17.33333333]]
Корни уравнения [-1.  0.  1.]


__Задание 4__  
Решить систему линейных уравнений методом Холецкого

$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$

$b=(531,-460,193)$<br><br>
$l_{11}=\sqrt{a_{11}}=\sqrt{81}=9$<br>
$l_{21}=\frac {a_{21}}{l_{11}}=-45/9=-5, \quad l_{31}=\frac {a_{31}}{l_{11}}=45/9=5$<br>
$l_{22}=\sqrt {a_{22}-l_{21}^2}=\sqrt{50-25}=5$<br>
$l_{32}=\frac {1}{l_{22}}\cdot(a_{32}-l_{21}l_{31})=\frac{1}{5}\cdot(-15+5*5)=2$<br>
$l_{33}=\sqrt {a_{33}-l_{31}^2-l_{32}^2}=\sqrt{38-25-4}=3$<br><br>
$L=\begin{pmatrix}
9 & 0 & 0 \\
-5 & 5 & 0 \\
5 & 2 & 3
\end{pmatrix}, \quad L^T=\begin{pmatrix}
9 & -5 & 5 \\
0 & 5 & 2 \\
0 & 0 & 3
\end{pmatrix}$<br><br>
$Ly=b$<br>
$\begin{cases}
9y_1 = 531 \\
-5y_1 + 5y_2 = -460 \\
5y_1 + 2y_2 + 3y_3 = 193
\end{cases}, \quad
\begin{cases}
y_1 = 59 \\
y_2 = -33 \\
y_3 = -12
\end{cases}$<br><br>
$L^Tx=y$<br>
$\begin{cases}
9x_1 -5x_2 +5x_3= 59 \\
5x_2 +2x_3= -33 \\
3x_3= -12
\end{cases}, \quad
\begin{cases}
x_1 = 6 \\
x_2 = -5 \\
x_3 = -4
\end{cases}$

In [15]:
A_ = sym.Matrix(((81,-45,45,531),(-45,50,-15,-460),(45,-15,38,193)))
sym.solve_linear_system(A_,x1,x2,x3)

{x1: 6, x2: -5, x3: -4}

In [16]:
print(linear_LU(np.array([[81,-45,45],[-45,50,-15],[45,-15,38]],float),np.array([531,-460,193])))

Матрица L:
[[ 1.          0.          0.        ]
 [-0.55555556  1.          0.        ]
 [ 0.55555556  0.4         1.        ]]
    Матрица U:
[[ 81. -45.  45.]
 [  0.  25.  10.]
 [  0.   0.   9.]]
Корни уравнения [ 6. -5. -4.]
